name: Triggers
run-name: Aprendiendo Triggers
on:
  push:
    branches:
      - main
    paths:
      - "**.js"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - "**.js"
  workflow_dispatch:
    inputs:
      alerta:
        description: Trigger a build
        required: true
        default: "true"
        type: choice
        options:
          - bajo
          - medio
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Saludar
        run: node hola-mundo.js