name: Triggers
on:
  push:
    branches:
      - main
    paths:
      - "**.js"
  pull_request:
    types: [opened, synchronize, reopened, closed]

    branches:
      - main
    paths:
      - "**.js"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Trigger a build"
